eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOME}
      
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
      hibernate: INFO

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: gambit
    bootstrap-servers: ${KAFKA_URL}
