logging:
 level:
   root: INFO
   org:
     springframework:
       web: DEBUG
     hibernate: INFO
spring:
 jpa:
   hibernate:
     ddl-auto: none
   properties:
     hibernate:
       show_sql: true
       use_sql_comments: true
       format_sql: true
 aop:
   auto: true
   
eureka:
  client:
    register-with-eureka: true
