#Server Configuration
server:
  port: 10004
security:
  basic:
    enabled: false

# H2 during development
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: skills-service
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: GAMBIT
#    password: p4ssw0rd
  jpa:
#    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none

#Logging Configuration
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
      hibernate: INFO
  