#Server Configuration
server:
  port: 10001
security:
  basic:
    enabled: false

# H2 during development
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: user-service
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: GAMBIT
#    password: p4ssw0rd
  jpa:
#    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none
  kafka:
    topic:
      trainer.register: trainer.register.t
      trainer.update: trainer.update.t
      trainer.delete: trainer.delete.t
      trainee.register: trainee.register.t
      trainee.update: trainee.update.t
      trainee.delete: trainee.delete.t
      user.register: user.register.t
      user.update: user.update.t
      user.delete: user.delete.t
